caja/urls.py
from django.urls import path
from . import views
from .views import cerrar_caja_lavanderia, historial_caja_lavanderia, historial_caja_cochera

urlpatterns = [
    path('caja/login/', views.caja_login, name='caja_login'),
    path('caja-general/', views.caja_view, name='cajaGeneral'),
    path('cerrar-caja-lavanderia/', cerrar_caja_lavanderia, name='cerrar_caja_lavanderia'),
    path('caja-lavanderia/', views.caja_lavanderia, name='cajaLavanderia'),
    path('caja/cerrar-caja-cochera/', views.cerrar_caja_cochera, name='cerrar_caja_cochera'),
    path('caja/caja-cochera/', views.caja_cochera, name='caja_cochera'),
    path('cajas-cerradas/', views.cajas_cerradas, name='cajas_cerradas'),
    path('detalle-caja/<int:caja_id>/', views.detalle_caja, name='detalle_caja'),
    path('historial-caja-lavanderia/', historial_caja_lavanderia, name='historial_caja_lavanderia'),
    path('historial-caja-cochera/', historial_caja_cochera, name='historial_caja_cochera'),
    path('detalle-caja/<int:pk>/', views.detalle_caja, name='detalle_caja'),
    path('reporte-general/', views.reporte_general, name='reporte_general'),
    path('generar-pdf-reporte-general/', views.generar_pdf_reporte_general, name='generar_pdf_reporte_general'),

    
]

sistema_vehicular/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import login_view

urlpatterns = [
    path('', login_view, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('estacionamiento/', include('estacionamiento.urls')),
    path('lavado/', include('lavado.urls')),
    path('tarifas/', include('tarifas_vehiculos.urls')), 
    path('caja/', include('caja.urls')),
]

lavado/models.py
from django.db import models
from tarifas_vehiculos.models import TarifaVehiculo
from django.utils import timezone
import barcode
from barcode.writer import ImageWriter


class Conductor(models.Model):
    dni = models.CharField(max_length=8)
    nombres = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    telefono = models.CharField(max_length=15)
    correo = models.EmailField()

    def __str__(self):
        return f"{self.nombres} {self.apellidos}"


class Vehiculo(models.Model):
    placa = models.CharField(max_length=10)
    modelo = models.CharField(max_length=100)
    marca = models.CharField(max_length=100)
    color = models.CharField(max_length=50)
    propietario = models.CharField(max_length=100)

    def __str__(self):
        return self.placa


class Lavanderia(models.Model):
    ESTADOS = (
        ('en_proceso', 'En proceso'),
        ('terminada', 'Terminada'),
    )

    tarifa_vehiculo = models.ForeignKey(TarifaVehiculo, on_delete=models.CASCADE)
    conductor = models.ForeignKey(Conductor, on_delete=models.CASCADE)
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)

    lavadero = models.BooleanField(default=False)
    cochera = models.BooleanField(default=False)
    total_a_pagar = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    tiempo = models.CharField(max_length=20, null=True, blank=True)
    precio_cochera = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    fecha_hora_entrada = models.DateTimeField(auto_now_add=True)
    fecha_hora_salida = models.DateTimeField(null=True, blank=True)
    efectivo = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    vuelto = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    estado = models.CharField(max_length=20, choices=ESTADOS, default='en_proceso')
    caja_cerrada = models.BooleanField(default=False)

    codigo_barras = models.ImageField(upload_to='codigos_barras/', blank=True)

    def registrar_salida(self):
        self.fecha_hora_salida = timezone.now()
        self.save()

    def calcular_total_a_pagar(self):
        total = 0
        if self.lavadero:
            total += self.tarifa_vehiculo.precio_lavado
        if self.cochera:
            total += self.precio_cochera or 0
        return total

    def save(self, *args, **kwargs):
        if not self.pk:
            codigo = f'{self.vehiculo.placa}-{self.conductor.dni}-{timezone.now().strftime("%Y%m%d")}'
            ean = barcode.get_barcode_class('code128')
            codigo_barras = ean(codigo, writer=ImageWriter())
            archivo_imagen = codigo_barras.save('codigo_barras')
            self.codigo_barras = archivo_imagen

        self.total_a_pagar = self.calcular_total_a_pagar()

        super().save(*args, **kwargs)

    def __str__(self):
        return f"Lavandería - {self.vehiculo.placa}"

tarifas_vehiculos/models.py
from django.db import models

class TarifaVehiculo(models.Model):
    TIPO_VEHICULO_CHOICES = (
        ('Automóvil', 'Automóvil'),
        ('Camioneta', 'Camioneta'),
        ('Moto', 'Moto'),
        
    )

    tipo_vehiculo = models.CharField(
        max_length=100, choices=TIPO_VEHICULO_CHOICES, unique=True)
    precio_manana = models.DecimalField(max_digits=10, decimal_places=2)
    precio_tarde = models.DecimalField(max_digits=10, decimal_places=2)
    precio_noche = models.DecimalField(max_digits=10, decimal_places=2)
    precio_dia_completo = models.DecimalField(max_digits=10, decimal_places=2)
    precio_lavado = models.DecimalField(max_digits=10, decimal_places=2)
    

    def __str__(self):
        return f"{self.tipo_vehiculo} - Precios"

lavado/forms.py
from django import forms
from .models import Lavanderia, Conductor, Vehiculo


class LavanderiaForm(forms.ModelForm):
  class Meta:
    model = Lavanderia
    fields = ['conductor', 'vehiculo', 'lavadero', 'cochera','tiempo', 'precio_cochera', 'tarifa_vehiculo']
    exclude = ['conductor', 'vehiculo']


class ConductorForm(forms.ModelForm):
    class Meta:
        model = Conductor
        fields = ['dni', 'nombres', 'apellidos', 'telefono', 'correo']


class VehiculoForm(forms.ModelForm):
  class Meta:
    model = Vehiculo
    fields = ['placa', 'modelo', 'marca', 'color', 'propietario']


class ServicioForm(forms.Form):
    cochera = forms.BooleanField(required=False)
    lavanderia = forms.BooleanField(required=False)

templates/lavanderia/detalles_lavanderia.html
{% extends 'layout.html' %} {% load static %} {% block main %}

<div class="container mt-4">
  <h5 class="mb-4">
    <i class="fas fa-clipboard-list"></i> Detalles de Registro
  </h5>

  <div class="form-container">
    <div class="row mt-4">
      <!-- Conductor -->
      <div class="col-md-6 border-right">
        <div class="form-group">
          <label for="dni">DNI:</label>
          <p class="card-text">{{ lavanderia.conductor.dni }}</p>
        </div>

        <div class="form-group">
          <label for="nombres">Nombres y Apellidos:</label>
          <p class="card-text">
            {{ lavanderia.conductor.nombres }} {{lavanderia.conductor.apellidos }}
          </p>
        </div>

        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="id_telefono">Teléfono:</label>
            <p class="card-text">{{ lavanderia.conductor.telefono }}</p>
          </div>
          <div class="form-group col-md-6">
            <label for="id_correo">Correo Electrónico:</label>
            <p class="card-text">{{ lavanderia.conductor.correo }}</p>
          </div>
        </div>

        <div class="row" style="margin-left: 10px">
          <div class="form-group form-check col-md-2">
            <label for="id_lavadero">Lavadero</label>
            <p class="card-text">
              {% if lavanderia.lavadero %}Sí{% else %}No{% endif %}
            </p>
          </div>

          <div class="form-group form-check col-md-2">
            <label for="id_cochera">Cochera</label>
            <p class="card-text">
              {% if lavanderia.cochera %}Sí{% else %}No{% endif %}
            </p>
          </div>
        </div>

        <div class="row">
          <div class="form-group col-md-4">
            <label for="id_tipo_vehiculo">Tipo de Vehículo:</label>
            <p class="card-text">
              {{ lavanderia.tarifa_vehiculo.tipo_vehiculo }}
            </p>
          </div>

          <div class="form-group col-md-4">
            <label for="id_tiempo">Tiempo:</label>
            <p class="card-text">{{ lavanderia.tiempo}}</p>
          </div>

          <div class="form-group col-md-4">
            <label for="id_precio">Precio:</label>
            <p class="card-text">{{ lavanderia.precio_cochera }}</p>
          </div>
        </div>
      </div>

      <!-- Vehículo -->
      <div class="col-md-6 border-right">
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="id_placa">Placa:</label>
            <p class="card-text">{{ lavanderia.vehiculo.placa }}</p>
          </div>

          <div class="form-group col-md-6">
            <label for="id_modelo">Modelo:</label>
            <p class="card-text">{{ lavanderia.vehiculo.modelo }}</p>
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="id_marca">Marca:</label>
            <p class="card-text">{{ lavanderia.vehiculo.marca }}</p>
          </div>

          <div class="form-group col-md-6">
            <label for="id_color">Color:</label>
            <p class="card-text">{{ lavanderia.vehiculo.color }}</p>
          </div>
        </div>

        <div class="form-group">
          <label for="id_propietario">Propietario:</label>
          <p class="card-text">{{ lavanderia.vehiculo.propietario }}</p>
        </div>

        <div class="row" style="margin-left: 10px">
          <div class="form-group form-check col-md-6">
            <label for="id_fecha_entrada">Fecha y Hora de Entrada:</label>
            <p class="card-text">{{ lavanderia.fecha_hora_entrada }}</p>
          </div>
        </div>

        <div class="form-group col-md-12 text-right">
            <a href="{% url 'accedersalida' %}?id={{ lavanderia.id }}" class="btn btn-danger btn-sm" style="background-color: #cb705d; color: white; width: 100px; padding: 10px; text-decoration: none; border-color: #cb705d;">
                Acceder
            </a>
        </div>

      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/lavanderia/editar_lavanderia.html

{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Registro </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/registro.css' %}">
    <script src="{% static 'js/registro.js' %}"></script>

</head>
<body>
    {% include 'layouts/navbar.html' %}
    {% include 'layouts/sidebar.html' %}

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

        <h5 class="card-title mt-5 mb-3"> <i class="fas fa-edit"></i> EDITAR REGISTRO</h5>

        <div class="form-container">
                        
            <form method="post" id="lavanderia-form">
                {% csrf_token %}
                
                <div class="row">
                    <!-- Conductor -->
                    <div class="col-md-6 border-right">

                        <div class="form-group">
                            <label for="dni">DNI:</label>
                            <input type="text" class="form-control" id="dni" name="dni" maxlength="8" value="{{ lavanderia.conductor.dni }}">
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="nombres">Nombres:</label>
                                    <input type="text" class="form-control" id="nombres" name="nombres" readonly value="{{ lavanderia.conductor.nombres }}">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="apellidos">Apellidos:</label>
                                    <input type="text" class="form-control" id="apellidos" name="apellidos" readonly value="{{ lavanderia.conductor.apellidos }}">
                                </div>
                            </div>
                        </div>                   

                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="id_telefono">Teléfono:</label>
                                <input type="text" class="form-control" id="id_telefono" name="telefono" value="{{ lavanderia.conductor.telefono }}">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="id_correo">Correo Electrónico:</label>
                                <input type="email" class="form-control" id="id_correo" name="correo" value="{{ lavanderia.conductor.correo }}">
                            </div>
                        </div>

                    </div>
        
                    <!-- Vehículo -->
                    <div class="col-md-6 border-right">

                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="id_placa">Placa:</label>
                                <input type="text" class="form-control" id="id_placa" name="placa" value="{{ lavanderia.vehiculo.placa }}">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="id_modelo">Modelo:</label>
                                <input type="text" class="form-control" id="id_modelo" name="modelo" value="{{ lavanderia.vehiculo.modelo }}">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="id_marca">Marca:</label>
                                <input type="text" class="form-control" id="id_marca" name="marca" value="{{ lavanderia.vehiculo.marca }}">
                            </div>

                            <div class="form-group col-md-6">
                                <label for="id_color">Color:</label>
                                <input type="text" class="form-control" id="id_color" name="color" value="{{ lavanderia.vehiculo.color }}">
                            </div>
                        </div>


                        <div class="form-group">
                            <label for="id_propietario">Propietario:</label>
                            <input type="text" class="form-control" id="id_propietario" name="propietario" value="{{ lavanderia.vehiculo.propietario }}">
                        </div>
                    </div>

                </div>

                <!-- Lavandería -->
                
                 <div class="row " style="margin-left: 10px;">
                    <div class="form-group form-check col-md-2">
                        <input type="checkbox" class="form-check-input" id="id_lavadero" name="lavadero" {% if lavanderia.lavadero %}checked{% endif %}>
                        <label class="form-check-label" for="id_lavadero">Lavadero</label>
                    </div>
                    <div class="form-group form-check col-md-2">
                        <input type="checkbox" class="form-check-input" id="id_cochera" name="cochera" {% if lavanderia.cochera %}checked{% endif %}>
                        <label class="form-check-label" for="id_cochera">Cochera</label>
                    </div>
                </div>

                             
                <div class="row">
                    
                    <div class="form-group col-md-2">
                        <label for="tarifa_vehiculo">Tarifa de Vehículo:</label>
                        <select id="tarifa_vehiculo" name="tarifa_vehiculo">
                            {% for tarifa in tarifas_vehiculo %}
                                <option value="{{ tarifa.id }}"
                                        data-precioManana="{{ tarifa.precio_manana }}"
                                        data-precioTarde="{{ tarifa.precio_tarde }}"
                                        data-precioNoche="{{ tarifa.precio_noche }}"
                                        data-precioDiaCompleto="{{ tarifa.precio_dia_completo }}"
                                        {% if tarifa.id == lavanderia.tarifa_vehiculo.id %}selected{% endif %}>
                                    {{ tarifa.tipo_vehiculo }}
                                </option>
                            {% endfor %}
                        </select>
                        
                    </div>
                    
            
                    <div class="form-group col-md-2">
                        <label for="tiempo">Tiempo:</label>
                        <select id="tiempo" name="tiempo">
                            <option value="manana" {% if lavanderia.tiempo == 'manana' %}selected{% endif %}>Mañana</option>
                            <option value="tarde" {% if lavanderia.tiempo == 'tarde' %}selected{% endif %}>Tarde</option>
                            <option value="noche" {% if lavanderia.tiempo == 'noche' %}selected{% endif %}>Noche</option>
                            <option value="dia_completo" {% if lavanderia.tiempo == 'dia_completo' %}selected{% endif %}>Día Completo</option>
                        </select>
                    </div>
            
                    <div class="form-group col-md-2">
                        <label for="precio">Precio de Cochera:</label>
                        <!-- El campo de precio debería ser modificable -->
                        <input type="text" id="precio" name="precio" value="{{ lavanderia.precio_cochera }}">
                    </div>

                    <div class="form-group col-md-6 text-right">
                        <button type="submit" class="btn-submit">Actualizar</button>
                    </div>
                </div>
               

            </form> 
        </div>


    </main>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Obtener elementos del DOM
            const tarifaSelect = document.getElementById('tarifa_vehiculo');
            const tiempoSelect = document.getElementById('tiempo');
            const precioInput = document.getElementById('precio');
    
            // Función para manejar el evento de cambio en los select
            function handleSelectChange() {
                const tarifaOption = tarifaSelect.options[tarifaSelect.selectedIndex];
                const tiempo = tiempoSelect.value;
    
                // Obtener el precio correspondiente del elemento seleccionado
                let precio;
                switch (tiempo) {
                    case 'manana':
                        precio = tarifaOption.getAttribute('data-precioManana');
                        break;
                    case 'tarde':
                        precio = tarifaOption.getAttribute('data-precioTarde');
                        break;
                    case 'noche':
                        precio = tarifaOption.getAttribute('data-precioNoche');
                        break;
                    case 'dia_completo':
                        precio = tarifaOption.getAttribute('data-precioDiaCompleto');
                        break;
                    default:
                        precio = 'Error: Tiempo del día inválido';
                }
    
                // Actualizar el campo de precio con el valor obtenido
                // Actualizar el campo de precio con el valor obtenido
                precioInput.value = precio || 'undefined'; 
           }
    
            // Agregar eventos de cambio a los select
            tarifaSelect.addEventListener('change', handleSelectChange);
            tiempoSelect.addEventListener('change', handleSelectChange);
    
            // Llamar a la función handleSelectChange inicialmente para establecer el precio
            handleSelectChange();
        });
    </script>


    <script>
        $(document).ready(function(){
            $('#dni').on('input', function(){
                var dni = $(this).val();
                if (dni.length === 8) {
                    $.ajax({
                        url: '{% url "obtener_nombres_apellidos" %}',
                        method: 'POST',
                        data: {
                            'dni': dni,
                            'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()
                        },
                        success: function(response){
                            $('#nombres').val(response.nombres);
                            $('#apellidos').val(response.apellidos);
                        },
                        error: function(xhr, errmsg, err){
                            console.log(xhr.status + ": " + xhr.responseText);
                        }
                    });
                } else {
                    $('#nombres').val('');
                    $('#apellidos').val('');
                }
            });
        });
    </script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html> 

templates/lavanderia/historialLavanderia.html
{% extends 'layout.html' %} {% load static %} {% block main %}

<div class="container">
  <div class="row justify-content-center">
    <div class="row w-100">
      <div class="col-md-6">
        <h4 class="mt-5 mb-3">HISTORIAL DE REGISTRO DE LAVADERO</h4>
      </div>
      <div class="col-md-6">
        <div class="container mt-5 mb-3">
          <form method="GET" action="{% url 'historial_lavanderia' %}" class="form-inline my-2 my-lg-0 justify-content-end">

            <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Buscar" name="q"/>

            <button class="btn btn-outline-success my-2 my-sm-0 mr-2" type="submit">  Buscar </button>

            <a href="{% url 'generar_pdf_lavadero' %}" class="btn btn-success my-2 my-sm-0" style="background-color: #45B649; border-color: #45B649;">
                <i class="fas fa-file-pdf"></i> Descargar PDF
            </a>

          </form>
        </div>
      </div>
    </div>

    <div class="table-responsive">
      <table class="table table-bordered table-striped table-hover">
        <thead class="thead-dark">
          <tr>
            <th>Placa</th>
            <th>Vehículo</th>
            <th>DNI</th>
            <th>Conductor</th>
            <th>Precio</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          {% for lavanderia in lavanderias %}
          <tr>
            <td>{{ lavanderia.vehiculo.placa }}</td>
            <td>{{ lavanderia.tarifa_vehiculo.tipo_vehiculo }}</td>
            <td>{{ lavanderia.conductor.dni }}</td>
            <td>
              {{ lavanderia.conductor.nombres }} {{lavanderia.conductor.apellidos }}
            </td>
            <td>{{ lavanderia.tarifa_vehiculo.precio_lavado }}</td>

            <td>
              {% if lavanderia.estado != 'terminada' %}
              <a
                href="{% url 'editar_lavanderia' lavanderia.id %}"
                class="btn btn-primary btn-sm"
                >Editar</a
              >
              <a
                href="{% url 'detalles_lavanderia' lavanderia.id %}"
                class="btn btn-info btn-sm"
                >Detalles</a
              >
              <button
                onclick="eliminarLavanderia({{ lavanderia.id }})"
                class="btn btn-danger btn-sm"
              >
                Eliminar
              </button>

              {% else %}
              <button class="btn btn-primary btn-sm" disabled>Editar</button>
              <button class="btn btn-info btn-sm" disabled>Detalles</button>
              <button class="btn btn-danger btn-sm" disabled>Eliminar</button>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

      <div class="container mt-3 mb-3 d-flex justify-content-between">
        <div class="mb-3">
          <p>
            {{ lavanderias|length }} registros mostrados de {{ total_registros}} totales
          </p>
        </div>

        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
            {% if lavanderias.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page=1">Primera</a>
            </li>
            <li class="page-item">
              <a
                class="page-link"
                href="?page={{ lavanderias.previous_page_number }}"
                >Anterior</a
              >
            </li>
            {% endif %} {% for num in lavanderias.paginator.page_range %} {% if lavanderias.number == num %}
            <li class="page-item active">
              <span class="page-link"
                >{{ num }} <span class="sr-only">(current)</span></span
              >
            </li>
            {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
            {% endif %} {% endfor %} {% if lavanderias.has_next %}
            <li class="page-item">
              <a
                class="page-link"
                href="?page={{ lavanderias.next_page_number }}"
                >Siguiente</a
              >
            </li>
            <li class="page-item">
              <a
                class="page-link"
                href="?page={{ lavanderias.paginator.num_pages }}"
                >Última</a
              >
            </li>
            {% endif %}
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>

<script>
  function eliminarLavanderia(id) {
    fetch(`/lavado/lavado/eliminar-lavanderia/${id}/`, {
      method: "POST",
      headers: {
        "X-CSRFToken": "{{ csrf_token }}",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({}),
    })
      .then((response) => response.json())
      .then((data) => {
        if (data.error) {
          alert(data.error);
        } else {
          alert(data.message);
          document.getElementById(`lavanderia-${id}`).remove();
        }
      })
      .catch((error) => console.error("Error:", error));
  }
</script>

{% endblock %}