caja/urls.py
from django.urls import path
from . import views
from .views import cerrar_caja_lavanderia, historial_caja_lavanderia, historial_caja_cochera

urlpatterns = [
    path('caja/login/', views.caja_login, name='caja_login'),
    path('caja-general/', views.caja_view, name='cajaGeneral'),
    path('cerrar-caja-lavanderia/', cerrar_caja_lavanderia, name='cerrar_caja_lavanderia'),
    path('caja-lavanderia/', views.caja_lavanderia, name='cajaLavanderia'),
    path('caja/cerrar-caja-cochera/', views.cerrar_caja_cochera, name='cerrar_caja_cochera'),
    path('caja/caja-cochera/', views.caja_cochera, name='caja_cochera'),
    path('cajas-cerradas/', views.cajas_cerradas, name='cajas_cerradas'),
    path('detalle-caja/<int:caja_id>/', views.detalle_caja, name='detalle_caja'),
    path('historial-caja-lavanderia/', historial_caja_lavanderia, name='historial_caja_lavanderia'),
    path('historial-caja-cochera/', historial_caja_cochera, name='historial_caja_cochera'),
    path('detalle-caja/<int:pk>/', views.detalle_caja, name='detalle_caja'),
    path('reporte-general/', views.reporte_general, name='reporte_general'),
    path('generar-pdf-reporte-general/', views.generar_pdf_reporte_general, name='generar_pdf_reporte_general'),

    
]

sistema_vehicular/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import login_view

urlpatterns = [
    path('', login_view, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('estacionamiento/', include('estacionamiento.urls')),
    path('lavado/', include('lavado.urls')),
    path('tarifas/', include('tarifas_vehiculos.urls')), 
    path('caja/', include('caja.urls')),
]

lavado/models.py
from django.db import models
from tarifas_vehiculos.models import TarifaVehiculo
from django.utils import timezone
import barcode
from barcode.writer import ImageWriter


class Conductor(models.Model):
    dni = models.CharField(max_length=8)
    nombres = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    telefono = models.CharField(max_length=15)
    correo = models.EmailField()

    def __str__(self):
        return f"{self.nombres} {self.apellidos}"


class Vehiculo(models.Model):
    placa = models.CharField(max_length=10)
    modelo = models.CharField(max_length=100)
    marca = models.CharField(max_length=100)
    color = models.CharField(max_length=50)
    propietario = models.CharField(max_length=100)

    def __str__(self):
        return self.placa


class Lavanderia(models.Model):
    ESTADOS = (
        ('en_proceso', 'En proceso'),
        ('terminada', 'Terminada'),
    )

    tarifa_vehiculo = models.ForeignKey(TarifaVehiculo, on_delete=models.CASCADE)
    conductor = models.ForeignKey(Conductor, on_delete=models.CASCADE)
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)

    lavadero = models.BooleanField(default=False)
    cochera = models.BooleanField(default=False)
    total_a_pagar = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    tiempo = models.CharField(max_length=20, null=True, blank=True)
    precio_cochera = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    fecha_hora_entrada = models.DateTimeField(auto_now_add=True)
    fecha_hora_salida = models.DateTimeField(null=True, blank=True)
    efectivo = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    vuelto = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    estado = models.CharField(max_length=20, choices=ESTADOS, default='en_proceso')
    caja_cerrada = models.BooleanField(default=False)

    codigo_barras = models.ImageField(upload_to='codigos_barras/', blank=True)

    def registrar_salida(self):
        self.fecha_hora_salida = timezone.now()
        self.save()

    def calcular_total_a_pagar(self):
        total = 0
        if self.lavadero:
            total += self.tarifa_vehiculo.precio_lavado
        if self.cochera:
            total += self.precio_cochera or 0
        return total

    def save(self, *args, **kwargs):
        if not self.pk:
            codigo = f'{self.vehiculo.placa}-{self.conductor.dni}-{timezone.now().strftime("%Y%m%d")}'
            ean = barcode.get_barcode_class('code128')
            codigo_barras = ean(codigo, writer=ImageWriter())
            archivo_imagen = codigo_barras.save('codigo_barras')
            self.codigo_barras = archivo_imagen

        self.total_a_pagar = self.calcular_total_a_pagar()

        super().save(*args, **kwargs)

    def __str__(self):
        return f"Lavandería - {self.vehiculo.placa}"

tarifas_vehiculos/models.py
from django.db import models

class TarifaVehiculo(models.Model):
    TIPO_VEHICULO_CHOICES = (
        ('Automóvil', 'Automóvil'),
        ('Camioneta', 'Camioneta'),
        ('Moto', 'Moto'),
        
    )

    tipo_vehiculo = models.CharField(
        max_length=100, choices=TIPO_VEHICULO_CHOICES, unique=True)
    precio_manana = models.DecimalField(max_digits=10, decimal_places=2)
    precio_tarde = models.DecimalField(max_digits=10, decimal_places=2)
    precio_noche = models.DecimalField(max_digits=10, decimal_places=2)
    precio_dia_completo = models.DecimalField(max_digits=10, decimal_places=2)
    precio_lavado = models.DecimalField(max_digits=10, decimal_places=2)
    

    def __str__(self):
        return f"{self.tipo_vehiculo} - Precios"

lavado/forms.py
from django import forms
from .models import Lavanderia, Conductor, Vehiculo


class LavanderiaForm(forms.ModelForm):
  class Meta:
    model = Lavanderia
    fields = ['conductor', 'vehiculo', 'lavadero', 'cochera','tiempo', 'precio_cochera', 'tarifa_vehiculo']
    exclude = ['conductor', 'vehiculo']


class ConductorForm(forms.ModelForm):
    class Meta:
        model = Conductor
        fields = ['dni', 'nombres', 'apellidos', 'telefono', 'correo']


class VehiculoForm(forms.ModelForm):
  class Meta:
    model = Vehiculo
    fields = ['placa', 'modelo', 'marca', 'color', 'propietario']


class ServicioForm(forms.Form):
    cochera = forms.BooleanField(required=False)
    lavanderia = forms.BooleanField(required=False)

templates/salidas/acceder_salida_cochera.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Acceder Salida</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/registro.css' %}">

</head>
<body>
    {% include 'layouts/navbar.html' %}
    {% include 'layouts/sidebar.html' %}

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

        <div class="container mt-4">

            <h5 class="mb-4"><i class="fas fa-sign-out-alt"></i> Detalles de Salida Cochera</h5>
    
            <div class="form-container">

                    <div class="row mt-4">

                        <div class="col-md-6 border-right">

                            <div class="form-group">
                                <label for="nombres">Placa:</label>
                                <p class="card-text">{{ cochera.vehiculo.placa }}</p>
                            </div>
                                
                            <div class="form-group">
                                <label for="nombres">Conductor:</label>
                                <p class="card-text">{{ cochera.conductor.nombres }} {{ cochera.conductor.apellidos }}</p>
                            </div>

                            <div class="row " style="margin-left: 10px;">
                                <div class="form-group form-check col-md-2">
                                    <label for="id_lavadero">Lavadero</label>
                                    <p class="card-text">{% if cochera.lavadero %}Sí{% else %}No{% endif %}</p>
                                </div>
        
                                <div class="form-group form-check col-md-2">
                                    <label for="id_cochera">Cochera</label>
                                    <p class="card-text">{% if cochera.cochera %}Sí{% else %}No{% endif %}</p>
                                </div>
                            </div>

                            <div class="row">
    
                                <div class="form-group col-md-6">
                                    <label for="id_tipo_vehiculo">Tipo de Vehículo:</label>
                                    <p class="card-text">{{ cochera.tarifa_vehiculo.tipo_vehiculo }} </p>
                                </div>
                                
                                <div class="form-group col-md-6">
                                    <label for="id_tiempo">Tiempo:</label>
                                    <p class="card-text">{{ cochera.tiempo }}</p>
                                </div>
            
                            </div>

                        </div>
            
                        <div class="col-md-6 border-right">

                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="cochera_id" value="{{ cochera.id }}">
                                <div class="row" style="margin-left: 10px;">
                                    <div class="form-group col-md-6">
                                        <label for="id_fecha_entrada">Fecha y Hora de Entrada:</label>
                                        <p class="card-text">{{ cochera.fecha_hora_entrada }}</p>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="id_fecha_entrada">Fecha y Hora de Salida:</label>
                                        <p id="fecha_hora_salida" class="card-text">{{ cochera.fecha_hora_salida|date:"d/m/Y H:i:s" }}</p>
                                    </div>
                                </div>
                                <div class="row" style="margin-left: 10px;">
                                    <div class="form-group col-md-6">
                                        {% if cochera.lavadero %}
                                            <label for="id_precio_laavdo">Precio por Lavado:</label>
                                            <p class="card-text">S/ {{ cochera.tarifa_vehiculo.precio_lavado }}</p>
                                        {% endif %}
                                    </div>
                                    <div class="form-group col-md-6">
                                        {% if cochera.cochera %}
                                            <label for="id_precio_cochera">Precio por Cochera:</label>
                                            <p class="card-text">S/ {{ cochera.precio_cochera }}</p>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="row" style="margin-left: 10px;">
                                    <div class="form-group col-md-6 mt-1">
                                        <label for="efectivo">Efectivo:</label>
                                        <input type="number" id="efectivo" name="efectivo" class="form-control" required min="0">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="vuelto">Vuelto:</label>
                                        <input type="text" id="vuelto" name="vuelto" class="form-control" readonly>
                                        <small id="error-mensaje" class="text-danger"></small>
                                    </div>
                                </div>
                                <div class="row" style="margin-left: 10px;">
                                    <h3>Total a pagar: S/ {{ cochera.total_a_pagar }}</h3>

                                    <div class="form-group col-md-4 text-right">
                                        
                                        <button type="submit" class="btn-submit" id="boton_pagar">Ir a Pagar</button>
                                    </div>

                                </div>
                            </form>

                        </div>

                    </div>

            </div>
        </div>

    </main>


    <script>

        function calcularVuelto() {
            var efectivo = parseFloat(document.getElementById('efectivo').value);
            if (!isNaN(efectivo) && efectivo >= 0) {
                var totalAPagar = parseFloat('{{ cochera.total_a_pagar }}');
                var vuelto = efectivo - totalAPagar;
                if (!isNaN(vuelto)) {
                    document.getElementById('vuelto').value = vuelto.toFixed(2);
                    document.getElementById('error-mensaje').textContent = '';
                } else {
                    document.getElementById('vuelto').value = '';
                    document.getElementById('error-mensaje').textContent = 'Error: ingrese un valor válido';
                }
            } else {
                document.getElementById('vuelto').value = '';
                document.getElementById('error-mensaje').textContent = 'Error: ingrese un número positivo';
            }
        }

        document.getElementById('efectivo').addEventListener('input', calcularVuelto);

        document.getElementById('boton_pagar').addEventListener('click', function() {
            calcularVuelto(); 
            var nuevaVentana = window.open('', '_blank');



            nuevaVentana.document.write(`
            
                <!DOCTYPE html>
                <html lang="es">
                <head>
                    <meta charset="UTF-8">
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <title>Ticket</title>
                    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
                    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
                
                    <style>
                        body {
                            font-family: Arial, sans-serif;
                            font-size: 12px;
                            width: 100mm;
                            margin: 2rem;
                            padding: 0;
                        }
                        .ticket-container {
                            text-align: center;
                            padding: 5px;                        
                        }
                        .ticket-container h2, .ticket-container h4, .ticket-container h3{
                            margin: 5px 0;
                        }
                        hr {
                            border: 0;
                            border-top: 1px dashed #000;
                            margin: 5px 0;
                        }
                        .ticket-container p {
                            text-align: center;
                        }
                    </style>
                </head>
                <body>
                    <div class="container border">

                        <div class="text-center">
                            <h2 class="font-weight-bold mb-4 mt-3">TICKET DE SALIDA</h2>
                            <h4 class="mb-3">ESTACIÓN DE RUTA TIPO II</h4>
                            <h4>"SAN PABLO"</h4>
                        </div>
                
                        <p>Placa: </p>
                        <h1>{{ cochera.vehiculo.placa }} </h1>
                        <hr>
                        <p>Tipo de Vehículo: {{ cochera.tarifa_vehiculo.tipo_vehiculo }}</p>
                        <hr>
                
                        <p>Fecha y Hora de Entrada: {{ cochera.fecha_hora_entrada }}</p>
                        <hr>
                
                        <p>Fecha y Hora de Salida: <span id="ticket_fecha_hora_salida">{{ cochera.fecha_hora_salida|date:"d/m/Y H:i:s" }}</span></p>
                        <hr>
                
                        <p>Tiempo: {{ cochera.tiempo }}</p>
                        <hr>
                
                        <h3>Total a pagar: S/ {{ cochera.total_a_pagar }}</h3> 
                
                        <div class="text-center">
                            <h5>Estación de Ruta Tipo II</h5>
                            <p> Gracias por su preferencia.</p>
                        </div>
                
                        {% comment %} <img src="{{ cochera.codigo_barras }}" alt="Código de Barras"> {% endcomment %}
                
                    </div>

                </body>
                </html>

            `);














            
            // Cerramos el documento HTML
            nuevaVentana.document.close();
            
            // Agregamos la instrucción de impresión directamente después de cerrar el documento HTML
            nuevaVentana.onload = function() {
                this.print();
            };
        });

        function actualizarFechaHoraSalida() {
            var fechaHoraSalidaElemento = document.getElementById('fecha_hora_salida');
            var ahora = new Date(); 
            var fechaFormateada = ('0' + ahora.getDate()).slice(-2) + '/' + ('0' + (ahora.getMonth() + 1)).slice(-2) + '/' + ahora.getFullYear();
            var horas = ahora.getHours().toString().padStart(2, '0');
            var minutos = ahora.getMinutes().toString().padStart(2, '0');
            var segundos = ahora.getSeconds().toString().padStart(2, '0');
            var horaFormateada = horas + ':' + minutos + ':' + segundos;
            fechaHoraSalidaElemento.textContent = fechaFormateada + ' , ' + horaFormateada;
        }    
        setInterval(actualizarFechaHoraSalida, 1000);
      
    </script>
    

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html> 

templates/salidas/accedersalida.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Acceder Salida</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/registro.css' %}">

</head>
<body>
    {% include 'layouts/navbar.html' %}
    {% include 'layouts/sidebar.html' %}

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

        <div class="container mt-4">

            <h5 class="mb-4"><i class="fas fa-sign-out-alt"></i> Detalles de Salida</h5>
    
            <div class="form-container">

                    <div class="row mt-4">

                        <div class="col-md-6 border-right">

                            <div class="form-group">
                                <label for="nombres">Placa:</label>
                                <p class="card-text">{{ lavanderia.vehiculo.placa }}</p>
                            </div>
                                
                            <div class="form-group">
                                <label for="nombres">Conductor:</label>
                                <p class="card-text">{{ lavanderia.conductor.nombres }} {{ lavanderia.conductor.apellidos }}</p>
                            </div>

                            <div class="row " style="margin-left: 10px;">
                                <div class="form-group form-check col-md-2">
                                    <label for="id_lavadero">Lavadero</label>
                                    <p class="card-text">{% if lavanderia.lavadero %}Sí{% else %}No{% endif %}</p>
                                </div>
        
                                <div class="form-group form-check col-md-2">
                                    <label for="id_cochera">Cochera</label>
                                    <p class="card-text">{% if lavanderia.cochera %}Sí{% else %}No{% endif %}</p>
                                </div>
                            </div>

                            <div class="row">
    
                                <div class="form-group col-md-6">
                                    <label for="id_tipo_vehiculo">Tipo de Vehículo:</label>
                                    <p class="card-text">{{ lavanderia.tarifa_vehiculo.tipo_vehiculo }} </p>
                                </div>
                                
                                <div class="form-group col-md-6">
                                    <label for="id_tiempo">Tiempo:</label>
                                    <p class="card-text">{{ lavanderia.tiempo }}</p>
                                </div>
            
                            </div>

                        </div>
            
                        <div class="col-md-6 border-right">

                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="lavanderia_id" value="{{ lavanderia.id }}">
                                <div class="row" style="margin-left: 10px;">
                                    <div class="form-group col-md-6">
                                        <label for="id_fecha_entrada">Fecha y Hora de Entrada:</label>
                                        <p class="card-text">{{ lavanderia.fecha_hora_entrada }}</p>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="id_fecha_entrada">Fecha y Hora de Salida:</label>
                                        <p id="fecha_hora_salida" class="card-text">{{ lavanderia.fecha_hora_salida|date:"d/m/Y H:i:s" }}</p>
                                    </div>
                                </div>
                                <div class="row" style="margin-left: 10px;">
                                    <div class="form-group col-md-6">
                                        {% if lavanderia.lavadero %}
                                            <label for="id_precio_laavdo">Precio por Lavado:</label>
                                            <p class="card-text">S/ {{ lavanderia.tarifa_vehiculo.precio_lavado }}</p>
                                        {% endif %}
                                    </div>
                                    <div class="form-group col-md-6">
                                        {% if lavanderia.cochera %}
                                            <label for="id_precio_cochera">Precio por Cochera:</label>
                                            <p class="card-text">S/ {{ lavanderia.precio_cochera }}</p>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="row" style="margin-left: 10px;">
                                    <div class="form-group col-md-6 mt-1">
                                        <label for="efectivo">Efectivo:</label>
                                        <input type="number" id="efectivo" name="efectivo" class="form-control" required min="0">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="vuelto">Vuelto:</label>
                                        <input type="text" id="vuelto" name="vuelto" class="form-control" readonly>
                                        <small id="error-mensaje" class="text-danger"></small>
                                    </div>
                                </div>
                                <div class="row" style="margin-left: 10px;">
                                    <h3>Total a pagar: S/ {{ lavanderia.total_a_pagar }}</h3>

                                    <div class="form-group col-md-4 text-right">
                                        
                                        <button type="submit" class="btn-submit" id="boton_pagar">Ir a Pagar</button>
                                    </div>

                                </div>
                            </form>

                        </div>

                    </div>

            </div>
        </div>

    </main>


    <script>

        function calcularVuelto() {
            var efectivo = parseFloat(document.getElementById('efectivo').value);
            if (!isNaN(efectivo) && efectivo >= 0) {
                var totalAPagar = parseFloat('{{ lavanderia.total_a_pagar }}');
                var vuelto = efectivo - totalAPagar;
                if (!isNaN(vuelto)) {
                    document.getElementById('vuelto').value = vuelto.toFixed(2);
                    document.getElementById('error-mensaje').textContent = '';
                } else {
                    document.getElementById('vuelto').value = '';
                    document.getElementById('error-mensaje').textContent = 'Error: ingrese un valor válido';
                }
            } else {
                document.getElementById('vuelto').value = '';
                document.getElementById('error-mensaje').textContent = 'Error: ingrese un número positivo';
            }
        }

        document.getElementById('efectivo').addEventListener('input', calcularVuelto);

        document.getElementById('boton_pagar').addEventListener('click', function() {
            calcularVuelto(); 
            var nuevaVentana = window.open('', '_blank');
            nuevaVentana.document.write(`
                <!DOCTYPE html>
                <html lang="es">
                <head>
                    <meta charset="UTF-8">
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <title>Ticket</title>
                    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
                    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
                
                     <style>
                        body {
                            font-family: Arial, sans-serif;
                            font-size: 12px;
                            width: 100mm;
                            margin: 2rem;
                            padding: 0;
                        }
                        .ticket-container {
                            text-align: center;
                            padding: 5px;                        
                        }
                        .ticket-container h2, .ticket-container h4, .ticket-container h3{
                            margin: 5px 0;
                        }
                        hr {
                            border: 0;
                            border-top: 1px dashed #000;
                            margin: 5px 0;
                        }
                        .ticket-container p {
                            text-align: center;
                        }
                    </style>
                </head>
                <body>
                    <div class="container border">

                        <div class="text-center">
                            <h2 class="font-weight-bold mb-4">TICKET DE SALIDA</h2>
                            <h4 class="mb-3">ESTACIÓN DE RUTA TIPO II</h4>
                            <h4>"SAN PABLO"</h4>
                        </div>
                
                        <p>Placa: </p>
                        <h1>{{ lavanderia.vehiculo.placa }} </h1>
                        <hr>
                        <p>Tipo de Vehículo: {{ lavanderia.tarifa_vehiculo.tipo_vehiculo }}</p>
                        <hr>
                
                        <p>Fecha y Hora de Entrada: {{ lavanderia.fecha_hora_entrada }}</p>
                        <hr>
                
                        <p>Fecha y Hora de Salida: <span id="ticket_fecha_hora_salida">{{ lavanderia.fecha_hora_salida|date:"d/m/Y H:i:s" }}</span></p>
                        <hr>
                
                        <p>Tiempo: {{ lavanderia.tiempo }}</p>
                        <hr>
                
                        <h3>Total a pagar: S/ {{ lavanderia.total_a_pagar }}</h3> 
                
                        <div class="text-center">
                            <h5>Estación de Ruta Tipo II</h5>
                            <p> Gracias por su preferencia.</p>
                        </div>
                
                        {% comment %} <img src="{{ lavanderia.codigo_barras }}" alt="Código de Barras"> {% endcomment %}
                
                    </div>

                </body>
                </html>
            `);
            // Cerramos el documento HTML
            nuevaVentana.document.close();
            
            // Agregamos la instrucción de impresión directamente después de cerrar el documento HTML
            nuevaVentana.onload = function() {
                this.print();
            };
        });

        function actualizarFechaHoraSalida() {
            var fechaHoraSalidaElemento = document.getElementById('fecha_hora_salida');
            var ahora = new Date(); 
            var fechaFormateada = ('0' + ahora.getDate()).slice(-2) + '/' + ('0' + (ahora.getMonth() + 1)).slice(-2) + '/' + ahora.getFullYear();
            var horas = ahora.getHours().toString().padStart(2, '0');
            var minutos = ahora.getMinutes().toString().padStart(2, '0');
            var segundos = ahora.getSeconds().toString().padStart(2, '0');
            var horaFormateada = horas + ':' + minutos + ':' + segundos;
            fechaHoraSalidaElemento.textContent = fechaFormateada + ' , ' + horaFormateada;
        }    
        setInterval(actualizarFechaHoraSalida, 1000);
      
    </script>
    

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html> 